// Generated by script/generate_wire.py. Do not edit.
import Foundation

struct WirePluginCommandInput: Codable, Sendable {
    let `id`: String
    let `instance`: String
    let `args`: String
}

struct WireSessionInfo: Codable, Sendable {
    let `id`: String
    let `cwd`: String
    let `name`: String?
    let `parentSessionId`: String?
    let `parentSessionName`: String?
    let `temporary`: Bool?
    let `model`: String
    let `thinkingLevel`: String
    let `configurationRevision`: UInt64
    let `createdAt`: String
    let `updatedAt`: String
}

enum WireWorkspaceState: String, Codable, Sendable {
    case value0 = "ready"
    case value1 = "unavailable"
}

struct WireWorkspaceLimits: Codable, Sendable {
    let `maxPathBytes`: Int
    let `maxPathComponents`: Int
    let `defaultDirectoryPageSize`: Int
    let `maxDirectoryPageSize`: Int
    let `maxDirectoryEntries`: Int
    let `maxDirectoryResponseBytes`: Int
    let `maxDirectoryObservationBytes`: Int
    let `maxPreviewBytes`: Int
    let `maxPreviewLines`: Int
    let `maxActiveRequests`: Int
    let `maxPendingRequests`: Int
}

struct WireWorkspaceRef: Codable, Sendable {
    let `sessionId`: String
    let `cwd`: String
    let `workspaceId`: String
    let `state`: WireWorkspaceState
    let `limits`: WireWorkspaceLimits
}

enum WireTranscriptContentKind: String, Codable, Sendable {
    case value0 = "text"
    case value1 = "thinking"
    case value2 = "toolCall"
    case value3 = "image"
    case value4 = "file"
    case value5 = "annotations"
}

enum WireAnnotationAnchorKind: String, Codable, Sendable {
    case value0 = "workspace_file"
    case value1 = "working_tree_diff"
}

struct WireWorkspaceFileAnnotationAnchor: Codable, Sendable {
    let `workspaceId`: String
    let `path`: String
    let `fileRevision`: String
    let `startLine`: Int
    let `endLine`: Int
}

struct WireWorkingTreeDiffAnnotationAnchor: Codable, Sendable, Equatable {
    let `targetId`: String
    let `targetRevision`: String
    let `path`: String
    let `fileRevision`: String
    let `side`: String
    let `startLine`: Int
    let `endLine`: Int
}

struct WireAnnotationAnchor: Codable, Sendable {
    let `kind`: WireAnnotationAnchorKind
    let `workspaceFile`: WireWorkspaceFileAnnotationAnchor?
    let `workingTreeDiff`: WireWorkingTreeDiffAnnotationAnchor?
}

struct WireDiffEndpoint: Codable, Sendable, Equatable {
    let `kind`: String
    let `oid`: String?
}

struct WirePinnedDiffTarget: Codable, Sendable, Equatable {
    let `workspaceId`: String
    let `kind`: String
    let `base`: WireDiffEndpoint
    let `head`: WireDiffEndpoint
}

struct WireAnnotationPreview: Codable, Sendable {
    let `startLine`: Int
    let `endLine`: Int
    let `text`: String
    let `truncated`: Bool?
}

struct WireSubmittedAnnotation: Codable, Sendable {
    let `originalAnnotationId`: UInt64
    let `anchor`: WireAnnotationAnchor
    let `diffTarget`: WirePinnedDiffTarget?
    let `body`: String
    let `preview`: WireAnnotationPreview
}

struct WireTranscriptContent: Codable, Sendable {
    let `kind`: WireTranscriptContentKind
    let `text`: String?
    let `toolCallId`: String?
    let `toolName`: String?
    let `arguments`: String?
    let `argumentsTruncated`: Bool?
    let `filename`: String?
    let `mediaType`: String?
    let `attachmentId`: String?
    let `annotations`: [WireSubmittedAnnotation]?
}

struct WireTranscriptMessage: Codable, Sendable {
    let `id`: String
    let `turnId`: String
    let `sequence`: Int64
    let `role`: String
    let `content`: [WireTranscriptContent]?
    let `stopReason`: String?
    let `errorMessage`: String?
    let `toolCallId`: String?
    let `toolName`: String?
    let `boundaryId`: String?
    let `boundaryKind`: String?
    let `boundarySource`: String?
    let `details`: WireJSON?
    let `isError`: Bool?
    let `createdAt`: String
}

struct WirePendingBoundary: Codable, Sendable {
    let `id`: String
    let `kind`: String
    let `source`: String?
    let `content`: [WireTranscriptContent]?
    let `details`: WireJSON?
    let `acceptedAt`: String
}

struct WireProviderRetry: Codable, Sendable {
    let `count`: Int
    let `retryAt`: String?
}

struct WireActiveCompaction: Codable, Sendable {
    let `id`: String
    let `runId`: String
}

struct WireSessionUsageCost: Codable, Sendable {
    let `input`: Double
    let `output`: Double
    let `cacheRead`: Double
    let `cacheWrite`: Double
    let `total`: Double
}

struct WireSessionUsage: Codable, Sendable {
    let `input`: Int
    let `output`: Int
    let `cacheRead`: Int
    let `cacheWrite`: Int
    let `reasoning`: Int
    let `totalTokens`: Int
    let `cost`: WireSessionUsageCost
}

struct WirePluginFooterStyle: Codable, Sendable {
    let `fg`: String?
    let `bg`: String?
    let `bold`: Bool?
    let `dim`: Bool?
    let `italic`: Bool?
    let `underline`: Bool?
    let `strikethrough`: Bool?
}

struct WirePluginFooterSegment: Codable, Sendable {
    let `text`: String
    let `style`: WirePluginFooterStyle
}

struct WirePluginFooterItem: Codable, Sendable {
    let `id`: String
    let `pluginId`: String
    let `instance`: String
    let `content`: [WirePluginFooterSegment]?
}

struct WirePluginFooter: Codable, Sendable {
    let `items`: [WirePluginFooterItem]?
    let `locationHidden`: Bool
}

struct WirePluginCommand: Codable, Sendable {
    let `id`: String
    let `localId`: String
    let `pluginId`: String
    let `instance`: String
    let `description`: String
    let `argName`: String?
    let `category`: String?
}

struct WirePromptCommand: Codable, Sendable {
    let `argumentHint`: String?
    let `name`: String
    let `description`: String
    let `source`: String
    let `location`: String
}

struct WireFollowUpQueue: Codable, Sendable {
    let `count`: Int
    let `previews`: [String]?
    let `annotationIds`: [UInt64]?
}

struct WireMCPServerStatus: Codable, Sendable {
    let `name`: String
    let `state`: String
    let `transport`: String
    let `toolCount`: Int
    let `oauthSaved`: Bool
    let `description`: String?
    let `source`: String
    let `configPath`: String?
    let `lastError`: String?
}

struct WireSubagentSource: Codable, Sendable {
    let `kind`: String
    let `path`: String
    let `pluginId`: String?
}

struct WireSubagentDefinition: Codable, Sendable {
    let `name`: String
    let `description`: String
    let `model`: String?
    let `source`: WireSubagentSource
}

struct WireSubagentDiagnostic: Codable, Sendable {
    let `severity`: String
    let `code`: String
    let `message`: String
    let `source`: WireSubagentSource
}

struct WireSubagentTask: Codable, Sendable {
    let `id`: String
    let `sequence`: UInt64
    let `state`: String
    let `cancellationGeneration`: UInt64
    let `queuedAt`: String
    let `startedAt`: String?
    let `finishedAt`: String?
    let `resultSummary`: String?
    let `error`: String?
}

struct WireSubagentConversation: Codable, Sendable {
    let `id`: String
    let `agentName`: String
    let `model`: String
    let `thinkingLevel`: String
    let `state`: String
    let `generation`: UInt64
    let `activeTaskId`: String?
    let `queuedTasks`: Int
    let `lastCompletedTaskId`: String?
    let `lastResultSummary`: String?
    let `updatedAt`: String
    let `tasks`: [WireSubagentTask]?
}

struct WireSubagentMailboxItem: Codable, Sendable {
    let `id`: String
    let `conversationId`: String
    let `taskId`: String
    let `agentName`: String
    let `state`: String
    let `summary`: String?
    let `error`: String?
    let `createdAt`: String
}

struct WirePluginInteractionOwner: Codable, Sendable {
    let `pluginId`: String
    let `instance`: String
}

enum WireInteractionKind: String, Codable, Sendable {
    case value0 = "confirm"
    case value1 = "input"
    case value2 = "select"
    case value3 = "guided"
}

struct WireInteractionOption: Codable, Sendable {
    let `id`: String
    let `label`: String
    let `detail`: String?
}

enum WireInteractionQuestionKind: String, Codable, Sendable {
    case value0 = "text"
    case value1 = "select"
    case value2 = "multiselect"
    case value3 = "boolean"
}

struct WireInteractionQuestion: Codable, Sendable {
    let `id`: String
    let `prompt`: String
    let `detail`: String?
    let `kind`: WireInteractionQuestionKind
    let `required`: Bool
    let `options`: [WireInteractionOption]?
}

struct WireInteractionRequest: Codable, Sendable {
    let `plugin`: WirePluginInteractionOwner?
    let `confirmLabel`: String?
    let `cancelLabel`: String?
    let `defaultValue`: Bool?
    let `placeholder`: String?
    let `initialValue`: String?
    let `filterable`: Bool?
    let `id`: String
    let `sessionId`: String
    let `runId`: String?
    let `toolCallId`: String?
    let `kind`: WireInteractionKind
    let `title`: String
    let `detail`: String?
    let `options`: [WireInteractionOption]?
    let `questions`: [WireInteractionQuestion]?
    let `createdAt`: String
    init(plugin: WirePluginInteractionOwner? = nil, confirmLabel: String? = nil, cancelLabel: String? = nil, defaultValue: Bool? = nil, placeholder: String? = nil, initialValue: String? = nil, filterable: Bool? = nil, id: String, sessionId: String, runId: String? = nil, toolCallId: String? = nil, kind: WireInteractionKind, title: String, detail: String? = nil, options: [WireInteractionOption]? = nil, questions: [WireInteractionQuestion]? = nil, createdAt: String) { self.plugin = plugin; self.confirmLabel = confirmLabel; self.cancelLabel = cancelLabel; self.defaultValue = defaultValue; self.placeholder = placeholder; self.initialValue = initialValue; self.filterable = filterable; self.id = id; self.sessionId = sessionId; self.runId = runId; self.toolCallId = toolCallId; self.kind = kind; self.title = title; self.detail = detail; self.options = options; self.questions = questions; self.createdAt = createdAt }
}

enum WireAnnotationStaleReason: String, Codable, Sendable {
    case value0 = "workspace_changed"
    case value1 = "target_changed"
    case value2 = "file_changed"
    case value3 = "resource_unavailable"
    case value4 = "validation_deferred"
}

struct WireAnnotationSummary: Codable, Sendable {
    let `id`: UInt64
    let `anchor`: WireAnnotationAnchor
    let `diffTarget`: WirePinnedDiffTarget?
    let `bodyPreview`: String
    let `preview`: String
    let `stale`: Bool?
    let `staleReason`: WireAnnotationStaleReason?
    let `validationDeferred`: Bool?
}

struct WireScratchpad: Codable, Sendable {
    let `ownerSessionId`: String
    let `content`: String
    let `revision`: String
    let `updatedAt`: String
}

struct WireSessionSnapshot: Codable, Sendable {
    let `session`: WireSessionInfo
    let `workspace`: WireWorkspaceRef?
    let `messages`: [WireTranscriptMessage]?
    let `previousMessageCursor`: String?
    let `hasMoreMessages`: Bool?
    let `pendingBoundaries`: [WirePendingBoundary]?
    let `activeRunId`: String?
    let `providerRetry`: WireProviderRetry?
    let `activeCompaction`: WireActiveCompaction?
    let `activeBashExecutionId`: String?
    let `eventStreamId`: String?
    let `eventCursor`: Int64?
    let `eventReplayFrom`: Int64?
    let `eventReplayAvailable`: Bool?
    let `contextTokens`: Int?
    let `contextWindow`: Int?
    let `usage`: WireSessionUsage
    let `pluginFooter`: WirePluginFooter?
    let `pluginCommands`: [WirePluginCommand]?
    let `promptCommands`: [WirePromptCommand]?
    let `followUps`: WireFollowUpQueue
    let `warnings`: [String]?
    let `mcpServers`: [WireMCPServerStatus]?
    let `mcpWarnings`: [String]?
    let `subagentDefinitions`: [WireSubagentDefinition]?
    let `subagentDiagnostics`: [WireSubagentDiagnostic]?
    let `subagentConversations`: [WireSubagentConversation]?
    let `subagentMailbox`: [WireSubagentMailboxItem]?
    let `pendingInteractions`: [WireInteractionRequest]?
    let `annotations`: [WireAnnotationSummary]?
    let `scratchpad`: WireScratchpad?
}

enum WireSessionEventKind: String, Codable, Sendable {
    case value0 = "run.started"
    case value1 = "message.user"
    case value2 = "assistant.started"
    case value3 = "assistant.text.delta"
    case value4 = "assistant.thinking.delta"
    case value5 = "assistant.completed"
    case value6 = "tool.planned"
    case value7 = "tool.started"
    case value8 = "tool.updated"
    case value9 = "tool.completed"
    case value10 = "compaction.started"
    case value11 = "compaction.completed"
    case value12 = "compaction.failed"
    case value13 = "provider.retry.scheduled"
    case value14 = "provider.retry.started"
    case value15 = "context.updated"
    case value16 = "usage.updated"
    case value17 = "run.finished"
    case value18 = "session.renamed"
    case value19 = "session.cwd.changed"
    case value20 = "subagent.changed"
    case value21 = "peer_query.changed"
    case value22 = "interaction.requested"
    case value23 = "interaction.resolved"
    case value24 = "annotation.created"
    case value25 = "annotation.updated"
    case value26 = "annotation.deleted"
    case value27 = "annotation.submitted"
    case value28 = "scratchpad.changed"
}

enum WireRunStatus: String, Codable, Sendable {
    case value0 = "queued"
    case value1 = "running"
    case value2 = "completed"
    case value3 = "failed"
    case value4 = "aborted"
    case value5 = "interrupted"
}

enum WireProviderErrorKind: String, Codable, Sendable {
    case value0 = "authentication"
    case value1 = "entitlement"
    case value2 = "usage_limit"
    case value3 = "rate_limit"
    case value4 = "transport"
    case value5 = "protocol"
}

struct WireAnnotation: Codable, Sendable {
    let `id`: UInt64
    let `sessionId`: String
    let `anchor`: WireAnnotationAnchor
    let `diffTarget`: WirePinnedDiffTarget?
    let `body`: String
    let `preview`: WireAnnotationPreview
    let `stale`: Bool?
    let `staleReason`: WireAnnotationStaleReason?
    let `validationDeferred`: Bool?
}

struct WireSessionEvent: Codable, Sendable {
    let `streamId`: String
    let `sequence`: Int64
    let `sessionId`: String
    let `turnId`: String
    let `runId`: String
    let `messageId`: String?
    let `kind`: WireSessionEventKind
    let `contentIndex`: Int?
    let `delta`: String?
    let `text`: String?
    let `thinking`: String?
    let `toolCallId`: String?
    let `toolName`: String?
    let `arguments`: String?
    let `argumentsTruncated`: Bool?
    let `content`: [WireTranscriptContent]?
    let `contentTruncated`: Bool?
    let `details`: WireJSON?
    let `detailsOmitted`: Bool?
    let `isError`: Bool?
    let `status`: WireRunStatus?
    let `errorKind`: WireProviderErrorKind?
    let `errorMessage`: String?
    let `compactionId`: String?
    let `providerRetry`: WireProviderRetry?
    let `contextTokens`: Int?
    let `contextWindow`: Int?
    let `usage`: WireSessionUsage?
    let `sessionName`: String?
    let `workspace`: WireWorkspaceRef?
    let `subagentConversationId`: String?
    let `subagentTaskId`: String?
    let `peerRequestId`: String?
    let `interaction`: WireInteractionRequest?
    let `interactionId`: String?
    let `interactionResolution`: String?
    let `annotationId`: UInt64?
    let `annotation`: WireAnnotation?
    let `annotationIds`: [UInt64]?
    let `acceptedMessageId`: String?
    let `scratchpad`: WireScratchpad?
}

struct WireSessionEventBatch: Codable, Sendable {
    let `streamId`: String?
    let `firstSequence`: Int64?
    let `lastSequence`: Int64?
    let `resyncRequired`: Bool?
    let `usageBaseline`: WireSessionUsage?
    let `events`: [WireSessionEvent]?
}

struct WireUpdateScratchpadInput: Codable, Sendable {
    let `expectedRevision`: String
    let `content`: String
}

struct WireGitHubPullRequest: Codable, Sendable {
    let `number`: Int
    let `url`: String
}

enum WireVCSHeadKind: String, Codable, Sendable {
    case value0 = "branch"
    case value1 = "detached"
    case value2 = "unborn"
}

struct WireVCSHead: Codable, Sendable {
    let `kind`: WireVCSHeadKind
    let `name`: String?
    let `oid`: String?
}

struct WireVCSStatus: Codable, Sendable {
    let `pullRequest`: WireGitHubPullRequest?
    let `root`: String
    let `head`: WireVCSHead
    let `dirty`: Bool
}

struct WireSessionVCSStatus: Codable, Sendable {
    let `sessionId`: String
    let `cwd`: String
    let `status`: WireVCSStatus?
}

struct WireTranscriptPage: Codable, Sendable {
    let `sessionId`: String
    let `messages`: [WireTranscriptMessage]?
    let `previousMessageCursor`: String?
    let `hasMoreMessages`: Bool?
}

struct WireSubagentTranscript: Codable, Sendable {
    let `conversationId`: String
    let `messages`: [WireTranscriptMessage]?
}

enum WireSubagentAction: String, Codable, Sendable {
    case value0 = "list_agents"
    case value1 = "start"
    case value2 = "message"
    case value3 = "inspect"
    case value4 = "wait"
    case value5 = "cancel"
    case value6 = "dismiss"
}

struct WireSubagentOperationInput: Codable, Sendable {
    let `action`: WireSubagentAction
    let `agent`: String?
    let `message`: String?
    let `conversationId`: String?
    let `taskId`: String?
    let `timeoutMs`: Int64?
    let `generation`: UInt64?
}

struct WireSubagentOperationResult: Codable, Sendable {
    let `definitions`: [WireSubagentDefinition]?
    let `diagnostics`: [WireSubagentDiagnostic]?
    let `conversation`: WireSubagentConversation?
    let `conversations`: [WireSubagentConversation]?
    let `task`: WireSubagentTask?
    let `tasks`: [WireSubagentTask]?
    let `timedOut`: Bool?
    let `dismissed`: Bool?
    let `warning`: String?
}

struct WireSubagentLiveEvent: Codable, Sendable {
    let `sequence`: Int64
    let `kind`: String
    let `turnId`: String?
    let `messageId`: String?
    let `contentIndex`: Int?
    let `delta`: String?
    let `text`: String?
    let `toolCallId`: String?
    let `toolName`: String?
    let `isError`: Bool?
}

struct WireSubagentLiveEventPage: Codable, Sendable {
    let `streamId`: String?
    let `firstSequence`: Int64?
    let `lastSequence`: Int64?
    let `resyncRequired`: Bool?
    let `events`: [WireSubagentLiveEvent]?
}

struct WirePromptInput: Codable, Sendable {
    let `text`: String
    let `attachmentIds`: [String]?
    let `annotationIds`: [UInt64]?
}

struct WirePromptCommandInput: Codable, Sendable {
    let `name`: String
    let `args`: String?
}

struct WireBashExecutionInput: Codable, Sendable {
    let `executionId`: String
    let `command`: String
    let `excludeFromContext`: Bool?
}

enum WireBashExecutionStatus: String, Codable, Sendable {
    case value0 = "running"
    case value1 = "completed"
    case value2 = "failed"
    case value3 = "aborted"
    case value4 = "interrupted"
}

struct WireBashExecution: Codable, Sendable {
    let `id`: String
    let `sessionId`: String
    let `sequence`: Int64
    let `command`: String
    let `status`: WireBashExecutionStatus
    let `output`: String?
    let `exitCode`: Int?
    let `excludeFromContext`: Bool?
    let `truncated`: Bool?
    let `timedOut`: Bool?
    let `errorMessage`: String?
    let `startedAt`: String
    let `completedAt`: String?
}

struct WireRunReservation: Codable, Sendable {
    let `sessionId`: String
    let `turnId`: String
    let `runId`: String
}

struct WirePromptSubmission: Codable, Sendable {
    let `reservation`: WireRunReservation?
    let `queued`: Bool
    let `queue`: WireFollowUpQueue
}

struct WireRestoreFollowUpsResult: Codable, Sendable {
    let `messages`: [WirePromptInput]?
    let `queue`: WireFollowUpQueue
}

struct WirePromoteFollowUpsResult: Codable, Sendable {
    let `promoted`: Int
    let `queue`: WireFollowUpQueue
}

struct WireCreateSessionInput: Codable, Sendable {
    let `id`: String?
    let `cwd`: String
    let `name`: String?
    let `model`: String
    let `thinkingLevel`: String?
    let `temporary`: Bool?
}

struct WireRenameSessionInput: Codable, Sendable {
    let `name`: String
}

struct WireChangeCWDInput: Codable, Sendable {
    let `mutationId`: String
    let `path`: String
}

struct WireChangeWorkspaceCWDResult: Codable, Sendable {
    let `session`: WireSessionInfo
    let `workspace`: WireWorkspaceRef
}

enum WirePromptSectionKind: String, Codable, Sendable {
    case value0 = "core"
    case value1 = "feature"
    case value2 = "skillCatalog"
    case value3 = "plugin"
    case value4 = "context"
}

struct WirePromptSource: Codable, Sendable {
    let `sectionId`: String
    let `id`: String
    let `kind`: WirePromptSectionKind
    let `path`: String?
}

struct WirePromptDiagnostic: Codable, Sendable {
    let `severity`: String
    let `code`: String
    let `message`: String
    let `source`: WirePromptSource
}

struct WireReloadSessionResult: Codable, Sendable {
    let `sessionId`: String
    let `eventStreamId`: String
    let `sources`: [WirePromptSource]?
    let `diagnostics`: [WirePromptDiagnostic]?
    let `warnings`: [String]?
}

struct WireCompactSessionInput: Codable, Sendable {
    let `operationId`: String
}

struct WireCompactSessionResult: Codable, Sendable {
    let `operationId`: String
    let `compacted`: Bool
    let `checkpointId`: String?
    let `eventStreamId`: String
}

struct WireForkSessionInput: Codable, Sendable {
    let `id`: String?
    let `name`: String?
}

enum WireThinkingLevel: String, Codable, Sendable {
    case value0 = "off"
    case value1 = "minimal"
    case value2 = "low"
    case value3 = "medium"
    case value4 = "high"
    case value5 = "xhigh"
    case value6 = "max"
}

enum WireModelInputKind: String, Codable, Sendable {
    case value0 = "text"
    case value1 = "image"
}

struct WireModelCapability: Codable, Sendable {
    let `id`: String
    let `name`: String
    let `provider`: String
    let `api`: String
    let `contextWindow`: Int
    let `maxInputTokens`: Int?
    let `maxOutputTokens`: Int?
    let `thinkingLevels`: [WireThinkingLevel]?
    let `inputs`: [WireModelInputKind]?
    let `available`: Bool
}

struct WireModelCatalog: Codable, Sendable {
    let `models`: [WireModelCapability]?
}

struct WireConfigureSessionInput: Codable, Sendable {
    let `expectedRevision`: UInt64
    let `model`: String
    let `thinkingLevel`: WireThinkingLevel?
}

struct WireConfigureSessionResult: Codable, Sendable {
    let `session`: WireSessionInfo
    let `eventStreamId`: String
    let `compacted`: Bool?
    let `checkpointId`: String?
    let `warnings`: [String]?
}

struct WireFileIndexEntry: Codable, Sendable {
    let `path`: String
    let `isDir`: Bool?
}

struct WireSessionFileIndex: Codable, Sendable {
    let `sessionId`: String
    let `cwd`: String
    let `entries`: [WireFileIndexEntry]?
    let `truncated`: Bool
}

struct WireReadWorkspaceFileInput: Codable, Sendable {
    let `workspaceId`: String
    let `path`: String
    let `expectedFileRevision`: String?
}

struct WireWorkspaceFileRead: Codable, Sendable {
    let `sessionId`: String
    let `workspace`: WireWorkspaceRef
    let `path`: String
    let `revision`: String
    let `size`: Int64
    let `modifiedAt`: String?
    let `encoding`: String
    let `content`: String
    let `returnedBytes`: Int
    let `returnedLines`: Int
    let `truncated`: Bool
    let `truncationReason`: String?
}

struct WireAttachmentInfo: Codable, Sendable {
    let `id`: String
    let `sessionId`: String
    let `filename`: String
    let `mediaType`: String
    let `size`: Int64
    let `sha256`: String
    let `createdAt`: String
    let `width`: Int?
    let `height`: Int?
}

struct WireAttachmentResolutionInput: Codable, Sendable {
    let `attachmentIds`: [String]?
}

struct WireAttachmentResolution: Codable, Sendable {
    let `attachments`: [WireAttachmentInfo]?
    let `missingAttachmentIds`: [String]?
}

struct WireInteractionAnswer: Codable, Sendable {
    let `text`: String?
    let `boolean`: Bool?
    let `optionIds`: [String]?
    let `skipped`: Bool?
}

struct WireInteractionResponse: Codable, Sendable {
    let `requestId`: String
    let `cancelled`: Bool?
    let `confirmed`: Bool?
    let `value`: String?
    let `selectedOptionId`: String?
    let `answers`: [String: WireInteractionAnswer]?
}

struct WireCreateAnnotationInput: Codable, Sendable {
    let `anchor`: WireAnnotationAnchor
    let `body`: String
}

struct WireUpdateAnnotationInput: Codable, Sendable {
    let `annotationId`: UInt64
    let `body`: String
}

struct WireDeleteAnnotationInput: Codable, Sendable {
    let `annotationId`: UInt64
}

struct WireAnnotationPage: Codable, Sendable {
    let `sessionId`: String
    let `entries`: [WireAnnotation]?
    let `nextCursor`: String?
}

struct WireListDiffTargetsInput: Codable, Sendable {
    let `workspaceId`: String
}

struct WireDiffTargetMetadata: Codable, Sendable {
    let `label`: String
    let `refName`: String?
    let `baseRefName`: String?
    let `subject`: String?
    let `abbreviatedOid`: String?
    let `committedAt`: Int64?
}

struct WireDiffTargetEntry: Codable, Sendable {
    let `reference`: String
    let `targetId`: String
    let `kind`: String
    let `base`: WireDiffEndpoint
    let `head`: WireDiffEndpoint
    let `metadata`: WireDiffTargetMetadata
    let `annotationCount`: Int?
}

struct WireDiffTargetDiagnostic: Codable, Sendable {
    let `reason`: String
    let `count`: Int
}

struct WireDiffTargetCatalog: Codable, Sendable {
    let `sessionId`: String
    let `workspaceId`: String
    let `targets`: [WireDiffTargetEntry]?
    let `diagnostics`: [WireDiffTargetDiagnostic]?
}

struct WireObserveDiffInput: Codable, Sendable {
    let `workspaceId`: String
    let `targetReference`: String
    let `expectedTargetId`: String
    let `expectedTargetRevision`: String?
    let `pageSize`: Int?
    let `cursor`: String?
}

struct WireDiffTarget: Codable, Sendable {
    let `id`: String
    let `workspaceId`: String
    let `kind`: String
    let `repositoryPath`: String
    let `base`: WireDiffEndpoint?
    let `head`: WireDiffEndpoint?
}

struct WireDiffHead: Codable, Sendable {
    let `state`: String
    let `oid`: String?
}

struct WireDiffTruncation: Codable, Sendable {
    let `reason`: String
    let `count`: Int
}

struct WireDiffOmission: Codable, Sendable {
    let `reason`: String
    let `count`: Int
}

struct WireDiffObservation: Codable, Sendable {
    let `sessionId`: String
    let `target`: WireDiffTarget
    let `revision`: String
    let `head`: WireDiffHead
    let `indexSummary`: String
    let `complete`: Bool
    let `truncation`: WireDiffTruncation?
    let `omissions`: [WireDiffOmission]?
}

struct WireDiffSide: Codable, Sendable {
    let `kind`: String
    let `mode`: UInt32
}

struct WireDiffFileSummary: Codable, Sendable {
    let `path`: String
    let `fileRevision`: String?
    let `change`: String
    let `old`: WireDiffSide
    let `new`: WireDiffSide
    let `contentState`: String
    let `reason`: String?
    let `additions`: Int?
    let `deletions`: Int?
}

struct WireWorkingTreePage: Codable, Sendable {
    let `observation`: WireDiffObservation
    let `files`: [WireDiffFileSummary]?
    let `nextCursor`: String?
}

struct WireReadFileDiffInput: Codable, Sendable {
    let `targetId`: String
    let `targetRevision`: String
    let `path`: String
    let `expectedFileRevision`: String?
    let `annotationId`: UInt64?
    let `pageSize`: Int?
    let `maxHunks`: Int?
    let `cursor`: String?
}

struct WireDiffComputation: Codable, Sendable {
    let `state`: String
    let `reason`: String?
}

struct WireDiffLine: Codable, Sendable {
    let `kind`: String
    let `oldLine`: Int?
    let `newLine`: Int?
    let `content`: String
    let `hasTerminatingLF`: Bool
}

struct WireDiffHunk: Codable, Sendable {
    let `oldStart`: Int
    let `oldCount`: Int
    let `newStart`: Int
    let `newCount`: Int
    let `continuedBefore`: Bool
    let `continuedAfter`: Bool
    let `lines`: [WireDiffLine]?
}

struct WireFileDiffPage: Codable, Sendable {
    let `observation`: WireDiffObservation
    let `file`: WireDiffFileSummary
    let `computation`: WireDiffComputation
    let `hunks`: [WireDiffHunk]?
    let `nextCursor`: String?
}

enum WireDiffErrorCode: String, Codable, Sendable {
    case value0 = "invalid_path"
    case value1 = "not_repository"
    case value2 = "unsupported_repository"
    case value3 = "stale_workspace"
    case value4 = "stale_target"
    case value5 = "stale_file"
    case value6 = "stale_cursor"
    case value7 = "not_found"
    case value8 = "permission_denied"
    case value9 = "limit_exceeded"
    case value10 = "capacity_exceeded"
    case value11 = "repository_unavailable"
    case value12 = "unavailable"
}

struct WireDiffError: Codable, Sendable {
    let `code`: WireDiffErrorCode
    let `message`: String
    let `details`: [String: String]?
}

let kitWireVersion = 40
