"""Generate the read-only Swift wire graph from canonical Go JSON-tagged structs.

Fails on unsupported declarations rather than silently inventing a wire shape.
Run with --check in CI. Arrays/maps are nullable because Go encodes nil as null.
"""
import re
import sys
from pathlib import Path
root = Path(__file__).resolve().parents[3]
source = '\n'.join(p.read_text() for p in sorted((root / 'internal/protocol').glob('*.go')) if not p.name.endswith('_test.go'))
structs = dict(re.findall(r'type (\w+) struct \{\n(.*?)\n\}', source, re.S))
aliases = set(re.findall(r'type (\w+) string', source))
output = ['// Generated by script/generate_wire.py. Do not edit.', 'import Foundation', '']
seen = set()
def emit(name):
 if name in seen: return
 seen.add(name)
 if name in aliases:
  values = re.findall(r'\b\w+\s+' + name + r'\s*=\s*"([^"]+)"', source)
  if not values: raise ValueError(name)
  output.append('enum Wire'+name+': String, Codable, Sendable {')
  for n,v in enumerate(dict.fromkeys(values)): output.append('    case value'+str(n)+' = "'+v+'"')
  output.append('}\n'); return
 fields=[]
 for line in structs[name].splitlines():
  line=line.strip()
  if not line or line.startswith('//'): continue
  match=re.fullmatch(r'\w+\s+(\S+)\s+`json:"([^",]+)(,omitempty)?"`',line)
  if not match: raise ValueError(line)
  typ,key,omit=match.groups()
  optional=bool(omit) or typ.startswith(('*','[]','map['))
  def swift(t):
   if t.startswith('*'):return swift(t[1:])
   if t.startswith('[]'):return '['+swift(t[2:])+']'
   if t.startswith('map[string]'):return '[String: '+swift(t[11:])+']'
   primitive={'string':'String','int':'Int','int64':'Int64','uint64':'UInt64','bool':'Bool','float64':'Double','json.RawMessage':'WireJSON','time.Time':'String'}
   if t in primitive:return primitive[t]
   emit(t);return 'Wire'+t
  fields.append('    let `'+key+'`: '+swift(typ)+('?' if optional else ''))
 output.append('struct Wire'+name+': Codable, Sendable {\n'+'\n'.join(fields)+'\n}\n')
for name in ['SessionInfo','SessionSnapshot','SessionEventBatch','SessionVCSStatus','TranscriptPage','SubagentTranscript','SubagentOperationInput','SubagentOperationResult','SubagentLiveEventPage','PromptInput','PromptCommandInput','BashExecutionInput','PromptSubmission','RestoreFollowUpsResult','PromoteFollowUpsResult','CreateSessionInput','RenameSessionInput','ChangeCWDInput','ChangeWorkspaceCWDResult','ReloadSessionResult','CompactSessionInput','CompactSessionResult','ForkSessionInput','ModelCatalog','ConfigureSessionInput','ConfigureSessionResult','SessionFileIndex','ReadWorkspaceFileInput','WorkspaceFileRead','AttachmentInfo','AttachmentResolutionInput','AttachmentResolution','InteractionResponse']: emit(name)
version=re.search(r'SessionProtocolVersion = (\d+)',(root/'internal/version/version.go').read_text()).group(1)
output.append('let kitWireVersion = '+version+'\n')
path=root/'apps/macos/Sources/Kit/Client/Wire.generated.swift'
text='\n'.join(output)
if '--check' in sys.argv:
 if path.read_text()!=text: sys.exit('Swift wire types are stale; run script/generate_wire.py')
else:path.write_text(text)
