// Package aliasgen generates the parent API package's contract aliases.
package aliasgen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"sort"
)

var reservedTypes = map[string]bool{
	"BashExecution":    true,
	"PromptSubmission": true,
}

var renamedTypes = map[string]string{
	"BashState": "BashExecution",
	"Message":   "PromptInput",
}

// Generate returns the generated alias source for contractDir.
func Generate(contractDir string) ([]byte, error) {
	packages, err := parser.ParseDir(token.NewFileSet(), contractDir, func(info os.FileInfo) bool {
		return info.Name() != "" && !bytes.HasSuffix([]byte(info.Name()), []byte("_test.go"))
	}, 0)
	if err != nil {
		return nil, fmt.Errorf("parse contract package: %w", err)
	}
	pkg := packages["contract"]
	if pkg == nil {
		return nil, fmt.Errorf("contract package not found in %s", contractDir)
	}

	var types, constants []string
	for _, file := range pkg.Files {
		for _, declaration := range file.Decls {
			general, ok := declaration.(*ast.GenDecl)
			if !ok {
				continue
			}
			for _, specification := range general.Specs {
				switch value := specification.(type) {
				case *ast.TypeSpec:
					if value.Name.IsExported() && !reservedTypes[value.Name.Name] {
						types = append(types, value.Name.Name)
					}
				case *ast.ValueSpec:
					if general.Tok != token.CONST {
						continue
					}
					for _, name := range value.Names {
						if name.IsExported() {
							constants = append(constants, name.Name)
						}
					}
				}
			}
		}
	}
	sort.Strings(types)
	sort.Strings(constants)

	var output bytes.Buffer
	output.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	output.WriteString("package kit\n\n")
	output.WriteString("import \"github.com/akonwi/kit/api/contract\"\n\n")
	output.WriteString("type (\n")
	for _, name := range types {
		fmt.Fprintf(&output, "\t%s = contract.%s\n", name, name)
	}
	var renamed []string
	for name := range renamedTypes {
		renamed = append(renamed, name)
	}
	sort.Strings(renamed)
	for _, name := range renamed {
		fmt.Fprintf(&output, "\t%s = contract.%s\n", name, renamedTypes[name])
	}
	output.WriteString(")\n\n")
	output.WriteString("const (\n")
	for _, name := range constants {
		fmt.Fprintf(&output, "\t%s = contract.%s\n", name, name)
	}
	output.WriteString(")\n")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated aliases: %w", err)
	}
	return formatted, nil
}
