// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
internal protocol APIProtocol: Sendable {
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/plugin-commands`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/plugin-commands/post(executePluginCommand)`.
    func executePluginCommand(_ input: Operations.ExecutePluginCommand.Input) async throws -> Operations.ExecutePluginCommand.Output
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/plugin-toasts`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/plugin-toasts/get(streamPluginToasts)`.
    func streamPluginToasts(_ input: Operations.StreamPluginToasts.Input) async throws -> Operations.StreamPluginToasts.Output
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/scratchpad`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/scratchpad/get(getScratchpad)`.
    func getScratchpad(_ input: Operations.GetScratchpad.Input) async throws -> Operations.GetScratchpad.Output
    /// - Remark: HTTP `PUT /v1/sessions/{sessionID}/scratchpad`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/scratchpad/put(updateScratchpad)`.
    func updateScratchpad(_ input: Operations.UpdateScratchpad.Input) async throws -> Operations.UpdateScratchpad.Output
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/vcs`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/vcs/get(getSessionVCS)`.
    func getSessionVCS(_ input: Operations.GetSessionVCS.Input) async throws -> Operations.GetSessionVCS.Output
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/vcs/events`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/vcs/events/get(streamSessionVCS)`.
    func streamSessionVCS(_ input: Operations.StreamSessionVCS.Input) async throws -> Operations.StreamSessionVCS.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/plugin-commands`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/plugin-commands/post(executePluginCommand)`.
    internal func executePluginCommand(
        path: Operations.ExecutePluginCommand.Input.Path,
        headers: Operations.ExecutePluginCommand.Input.Headers,
        body: Operations.ExecutePluginCommand.Input.Body
    ) async throws -> Operations.ExecutePluginCommand.Output {
        try await executePluginCommand(Operations.ExecutePluginCommand.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/plugin-toasts`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/plugin-toasts/get(streamPluginToasts)`.
    internal func streamPluginToasts(
        path: Operations.StreamPluginToasts.Input.Path,
        headers: Operations.StreamPluginToasts.Input.Headers
    ) async throws -> Operations.StreamPluginToasts.Output {
        try await streamPluginToasts(Operations.StreamPluginToasts.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/scratchpad`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/scratchpad/get(getScratchpad)`.
    internal func getScratchpad(
        path: Operations.GetScratchpad.Input.Path,
        headers: Operations.GetScratchpad.Input.Headers
    ) async throws -> Operations.GetScratchpad.Output {
        try await getScratchpad(Operations.GetScratchpad.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PUT /v1/sessions/{sessionID}/scratchpad`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/scratchpad/put(updateScratchpad)`.
    internal func updateScratchpad(
        path: Operations.UpdateScratchpad.Input.Path,
        headers: Operations.UpdateScratchpad.Input.Headers,
        body: Operations.UpdateScratchpad.Input.Body
    ) async throws -> Operations.UpdateScratchpad.Output {
        try await updateScratchpad(Operations.UpdateScratchpad.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/vcs`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/vcs/get(getSessionVCS)`.
    internal func getSessionVCS(
        path: Operations.GetSessionVCS.Input.Path,
        headers: Operations.GetSessionVCS.Input.Headers
    ) async throws -> Operations.GetSessionVCS.Output {
        try await getSessionVCS(Operations.GetSessionVCS.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/vcs/events`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/vcs/events/get(streamSessionVCS)`.
    internal func streamSessionVCS(
        path: Operations.StreamSessionVCS.Input.Path,
        headers: Operations.StreamSessionVCS.Input.Headers
    ) async throws -> Operations.StreamSessionVCS.Output {
        try await streamSessionVCS(Operations.StreamSessionVCS.Input(
            path: path,
            headers: headers
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
internal enum Servers {}
