// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
internal protocol APIProtocol: Sendable {
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/scratchpad`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/scratchpad/get(getScratchpad)`.
    func getScratchpad(_ input: Operations.GetScratchpad.Input) async throws -> Operations.GetScratchpad.Output
    /// - Remark: HTTP `PUT /v1/sessions/{sessionID}/scratchpad`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/scratchpad/put(updateScratchpad)`.
    func updateScratchpad(_ input: Operations.UpdateScratchpad.Input) async throws -> Operations.UpdateScratchpad.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/scratchpad`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/scratchpad/get(getScratchpad)`.
    internal func getScratchpad(
        path: Operations.GetScratchpad.Input.Path,
        headers: Operations.GetScratchpad.Input.Headers
    ) async throws -> Operations.GetScratchpad.Output {
        try await getScratchpad(Operations.GetScratchpad.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PUT /v1/sessions/{sessionID}/scratchpad`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/scratchpad/put(updateScratchpad)`.
    internal func updateScratchpad(
        path: Operations.UpdateScratchpad.Input.Path,
        headers: Operations.UpdateScratchpad.Input.Headers,
        body: Operations.UpdateScratchpad.Input.Body
    ) async throws -> Operations.UpdateScratchpad.Output {
        try await updateScratchpad(Operations.UpdateScratchpad.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
internal enum Servers {}
