// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
internal protocol APIProtocol: Sendable {
    /// - Remark: HTTP `GET /v1/sessions`.
    /// - Remark: Generated from `#/paths//v1/sessions/get(listSessions)`.
    func listSessions(_ input: Operations.ListSessions.Input) async throws -> Operations.ListSessions.Output
    /// - Remark: HTTP `POST /v1/sessions`.
    /// - Remark: Generated from `#/paths//v1/sessions/post(createSession)`.
    func createSession(_ input: Operations.CreateSession.Input) async throws -> Operations.CreateSession.Output
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/get(getSession)`.
    func getSession(_ input: Operations.GetSession.Input) async throws -> Operations.GetSession.Output
    /// - Remark: HTTP `PATCH /v1/sessions/{sessionID}`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/patch(renameSession)`.
    func renameSession(_ input: Operations.RenameSession.Input) async throws -> Operations.RenameSession.Output
    /// - Remark: HTTP `DELETE /v1/sessions/{sessionID}`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/delete(deleteSession)`.
    func deleteSession(_ input: Operations.DeleteSession.Input) async throws -> Operations.DeleteSession.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/compact`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/compact/post(compactSession)`.
    func compactSession(_ input: Operations.CompactSession.Input) async throws -> Operations.CompactSession.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/configure`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/configure/post(configureSession)`.
    func configureSession(_ input: Operations.ConfigureSession.Input) async throws -> Operations.ConfigureSession.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/cwd`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/cwd/post(changeSessionCWD)`.
    func changeSessionCWD(_ input: Operations.ChangeSessionCWD.Input) async throws -> Operations.ChangeSessionCWD.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/dispose`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/dispose/post(disposeTemporarySession)`.
    func disposeTemporarySession(_ input: Operations.DisposeTemporarySession.Input) async throws -> Operations.DisposeTemporarySession.Output
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/events`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/events/get(getSessionEventPage)`.
    func getSessionEventPage(_ input: Operations.GetSessionEventPage.Input) async throws -> Operations.GetSessionEventPage.Output
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/events/stream`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/events/stream/get(streamSessionEvents)`.
    func streamSessionEvents(_ input: Operations.StreamSessionEvents.Input) async throws -> Operations.StreamSessionEvents.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/forks`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/forks/post(forkSession)`.
    func forkSession(_ input: Operations.ForkSession.Input) async throws -> Operations.ForkSession.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/interactions/{interactionID}/response`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/interactions/{interactionID}/response/post(respondInteraction)`.
    func respondInteraction(_ input: Operations.RespondInteraction.Input) async throws -> Operations.RespondInteraction.Output
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/messages`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/messages/get(getMessagePage)`.
    func getMessagePage(_ input: Operations.GetMessagePage.Input) async throws -> Operations.GetMessagePage.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/plugin-commands`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/plugin-commands/post(executePluginCommand)`.
    func executePluginCommand(_ input: Operations.ExecutePluginCommand.Input) async throws -> Operations.ExecutePluginCommand.Output
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/plugin-toasts`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/plugin-toasts/get(streamPluginToasts)`.
    func streamPluginToasts(_ input: Operations.StreamPluginToasts.Input) async throws -> Operations.StreamPluginToasts.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/reload`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/reload/post(reloadSession)`.
    func reloadSession(_ input: Operations.ReloadSession.Input) async throws -> Operations.ReloadSession.Output
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/scratchpad`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/scratchpad/get(getScratchpad)`.
    func getScratchpad(_ input: Operations.GetScratchpad.Input) async throws -> Operations.GetScratchpad.Output
    /// - Remark: HTTP `PUT /v1/sessions/{sessionID}/scratchpad`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/scratchpad/put(updateScratchpad)`.
    func updateScratchpad(_ input: Operations.UpdateScratchpad.Input) async throws -> Operations.UpdateScratchpad.Output
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/transcript`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/transcript/get(getTranscriptPage)`.
    func getTranscriptPage(_ input: Operations.GetTranscriptPage.Input) async throws -> Operations.GetTranscriptPage.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/turns/follow-ups/promote`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/follow-ups/promote/post(promoteTurnFollowUps)`.
    func promoteTurnFollowUps(_ input: Operations.PromoteTurnFollowUps.Input) async throws -> Operations.PromoteTurnFollowUps.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/turns/follow-ups/restore`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/follow-ups/restore/post(restoreTurnFollowUps)`.
    func restoreTurnFollowUps(_ input: Operations.RestoreTurnFollowUps.Input) async throws -> Operations.RestoreTurnFollowUps.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/turns/prompt`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/prompt/post(prompt)`.
    func prompt(_ input: Operations.Prompt.Input) async throws -> Operations.Prompt.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/turns/prompt-commands`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/prompt-commands/post(startPromptCommand)`.
    func startPromptCommand(_ input: Operations.StartPromptCommand.Input) async throws -> Operations.StartPromptCommand.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/turns/prompts`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/prompts/post(startPrompt)`.
    func startPrompt(_ input: Operations.StartPrompt.Input) async throws -> Operations.StartPrompt.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/turns/submissions`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/submissions/post(submitPrompt)`.
    func submitPrompt(_ input: Operations.SubmitPrompt.Input) async throws -> Operations.SubmitPrompt.Output
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/turns/{turnID}`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/{turnID}/get(getTurn)`.
    func getTurn(_ input: Operations.GetTurn.Input) async throws -> Operations.GetTurn.Output
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/turns/{turnID}/abort`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/{turnID}/abort/post(abortTurn)`.
    func abortTurn(_ input: Operations.AbortTurn.Input) async throws -> Operations.AbortTurn.Output
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/vcs`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/vcs/get(getSessionVCS)`.
    func getSessionVCS(_ input: Operations.GetSessionVCS.Input) async throws -> Operations.GetSessionVCS.Output
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/vcs/events`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/vcs/events/get(streamSessionVCS)`.
    func streamSessionVCS(_ input: Operations.StreamSessionVCS.Input) async throws -> Operations.StreamSessionVCS.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `GET /v1/sessions`.
    /// - Remark: Generated from `#/paths//v1/sessions/get(listSessions)`.
    internal func listSessions(
        query: Operations.ListSessions.Input.Query = .init(),
        headers: Operations.ListSessions.Input.Headers
    ) async throws -> Operations.ListSessions.Output {
        try await listSessions(Operations.ListSessions.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions`.
    /// - Remark: Generated from `#/paths//v1/sessions/post(createSession)`.
    internal func createSession(
        headers: Operations.CreateSession.Input.Headers,
        body: Operations.CreateSession.Input.Body
    ) async throws -> Operations.CreateSession.Output {
        try await createSession(Operations.CreateSession.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/get(getSession)`.
    internal func getSession(
        path: Operations.GetSession.Input.Path,
        headers: Operations.GetSession.Input.Headers
    ) async throws -> Operations.GetSession.Output {
        try await getSession(Operations.GetSession.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PATCH /v1/sessions/{sessionID}`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/patch(renameSession)`.
    internal func renameSession(
        path: Operations.RenameSession.Input.Path,
        headers: Operations.RenameSession.Input.Headers,
        body: Operations.RenameSession.Input.Body
    ) async throws -> Operations.RenameSession.Output {
        try await renameSession(Operations.RenameSession.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `DELETE /v1/sessions/{sessionID}`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/delete(deleteSession)`.
    internal func deleteSession(
        path: Operations.DeleteSession.Input.Path,
        headers: Operations.DeleteSession.Input.Headers
    ) async throws -> Operations.DeleteSession.Output {
        try await deleteSession(Operations.DeleteSession.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/compact`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/compact/post(compactSession)`.
    internal func compactSession(
        path: Operations.CompactSession.Input.Path,
        headers: Operations.CompactSession.Input.Headers,
        body: Operations.CompactSession.Input.Body
    ) async throws -> Operations.CompactSession.Output {
        try await compactSession(Operations.CompactSession.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/configure`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/configure/post(configureSession)`.
    internal func configureSession(
        path: Operations.ConfigureSession.Input.Path,
        headers: Operations.ConfigureSession.Input.Headers,
        body: Operations.ConfigureSession.Input.Body
    ) async throws -> Operations.ConfigureSession.Output {
        try await configureSession(Operations.ConfigureSession.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/cwd`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/cwd/post(changeSessionCWD)`.
    internal func changeSessionCWD(
        path: Operations.ChangeSessionCWD.Input.Path,
        headers: Operations.ChangeSessionCWD.Input.Headers,
        body: Operations.ChangeSessionCWD.Input.Body
    ) async throws -> Operations.ChangeSessionCWD.Output {
        try await changeSessionCWD(Operations.ChangeSessionCWD.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/dispose`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/dispose/post(disposeTemporarySession)`.
    internal func disposeTemporarySession(
        path: Operations.DisposeTemporarySession.Input.Path,
        headers: Operations.DisposeTemporarySession.Input.Headers
    ) async throws -> Operations.DisposeTemporarySession.Output {
        try await disposeTemporarySession(Operations.DisposeTemporarySession.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/events`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/events/get(getSessionEventPage)`.
    internal func getSessionEventPage(
        path: Operations.GetSessionEventPage.Input.Path,
        query: Operations.GetSessionEventPage.Input.Query = .init(),
        headers: Operations.GetSessionEventPage.Input.Headers
    ) async throws -> Operations.GetSessionEventPage.Output {
        try await getSessionEventPage(Operations.GetSessionEventPage.Input(
            path: path,
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/events/stream`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/events/stream/get(streamSessionEvents)`.
    internal func streamSessionEvents(
        path: Operations.StreamSessionEvents.Input.Path,
        query: Operations.StreamSessionEvents.Input.Query = .init(),
        headers: Operations.StreamSessionEvents.Input.Headers
    ) async throws -> Operations.StreamSessionEvents.Output {
        try await streamSessionEvents(Operations.StreamSessionEvents.Input(
            path: path,
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/forks`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/forks/post(forkSession)`.
    internal func forkSession(
        path: Operations.ForkSession.Input.Path,
        headers: Operations.ForkSession.Input.Headers,
        body: Operations.ForkSession.Input.Body
    ) async throws -> Operations.ForkSession.Output {
        try await forkSession(Operations.ForkSession.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/interactions/{interactionID}/response`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/interactions/{interactionID}/response/post(respondInteraction)`.
    internal func respondInteraction(
        path: Operations.RespondInteraction.Input.Path,
        headers: Operations.RespondInteraction.Input.Headers,
        body: Operations.RespondInteraction.Input.Body
    ) async throws -> Operations.RespondInteraction.Output {
        try await respondInteraction(Operations.RespondInteraction.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/messages`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/messages/get(getMessagePage)`.
    internal func getMessagePage(
        path: Operations.GetMessagePage.Input.Path,
        query: Operations.GetMessagePage.Input.Query = .init(),
        headers: Operations.GetMessagePage.Input.Headers
    ) async throws -> Operations.GetMessagePage.Output {
        try await getMessagePage(Operations.GetMessagePage.Input(
            path: path,
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/plugin-commands`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/plugin-commands/post(executePluginCommand)`.
    internal func executePluginCommand(
        path: Operations.ExecutePluginCommand.Input.Path,
        headers: Operations.ExecutePluginCommand.Input.Headers,
        body: Operations.ExecutePluginCommand.Input.Body
    ) async throws -> Operations.ExecutePluginCommand.Output {
        try await executePluginCommand(Operations.ExecutePluginCommand.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/plugin-toasts`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/plugin-toasts/get(streamPluginToasts)`.
    internal func streamPluginToasts(
        path: Operations.StreamPluginToasts.Input.Path,
        headers: Operations.StreamPluginToasts.Input.Headers
    ) async throws -> Operations.StreamPluginToasts.Output {
        try await streamPluginToasts(Operations.StreamPluginToasts.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/reload`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/reload/post(reloadSession)`.
    internal func reloadSession(
        path: Operations.ReloadSession.Input.Path,
        headers: Operations.ReloadSession.Input.Headers
    ) async throws -> Operations.ReloadSession.Output {
        try await reloadSession(Operations.ReloadSession.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/scratchpad`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/scratchpad/get(getScratchpad)`.
    internal func getScratchpad(
        path: Operations.GetScratchpad.Input.Path,
        headers: Operations.GetScratchpad.Input.Headers
    ) async throws -> Operations.GetScratchpad.Output {
        try await getScratchpad(Operations.GetScratchpad.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PUT /v1/sessions/{sessionID}/scratchpad`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/scratchpad/put(updateScratchpad)`.
    internal func updateScratchpad(
        path: Operations.UpdateScratchpad.Input.Path,
        headers: Operations.UpdateScratchpad.Input.Headers,
        body: Operations.UpdateScratchpad.Input.Body
    ) async throws -> Operations.UpdateScratchpad.Output {
        try await updateScratchpad(Operations.UpdateScratchpad.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/transcript`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/transcript/get(getTranscriptPage)`.
    internal func getTranscriptPage(
        path: Operations.GetTranscriptPage.Input.Path,
        query: Operations.GetTranscriptPage.Input.Query,
        headers: Operations.GetTranscriptPage.Input.Headers
    ) async throws -> Operations.GetTranscriptPage.Output {
        try await getTranscriptPage(Operations.GetTranscriptPage.Input(
            path: path,
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/turns/follow-ups/promote`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/follow-ups/promote/post(promoteTurnFollowUps)`.
    internal func promoteTurnFollowUps(
        path: Operations.PromoteTurnFollowUps.Input.Path,
        headers: Operations.PromoteTurnFollowUps.Input.Headers
    ) async throws -> Operations.PromoteTurnFollowUps.Output {
        try await promoteTurnFollowUps(Operations.PromoteTurnFollowUps.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/turns/follow-ups/restore`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/follow-ups/restore/post(restoreTurnFollowUps)`.
    internal func restoreTurnFollowUps(
        path: Operations.RestoreTurnFollowUps.Input.Path,
        headers: Operations.RestoreTurnFollowUps.Input.Headers
    ) async throws -> Operations.RestoreTurnFollowUps.Output {
        try await restoreTurnFollowUps(Operations.RestoreTurnFollowUps.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/turns/prompt`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/prompt/post(prompt)`.
    internal func prompt(
        path: Operations.Prompt.Input.Path,
        headers: Operations.Prompt.Input.Headers,
        body: Operations.Prompt.Input.Body
    ) async throws -> Operations.Prompt.Output {
        try await prompt(Operations.Prompt.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/turns/prompt-commands`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/prompt-commands/post(startPromptCommand)`.
    internal func startPromptCommand(
        path: Operations.StartPromptCommand.Input.Path,
        headers: Operations.StartPromptCommand.Input.Headers,
        body: Operations.StartPromptCommand.Input.Body
    ) async throws -> Operations.StartPromptCommand.Output {
        try await startPromptCommand(Operations.StartPromptCommand.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/turns/prompts`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/prompts/post(startPrompt)`.
    internal func startPrompt(
        path: Operations.StartPrompt.Input.Path,
        headers: Operations.StartPrompt.Input.Headers,
        body: Operations.StartPrompt.Input.Body
    ) async throws -> Operations.StartPrompt.Output {
        try await startPrompt(Operations.StartPrompt.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/turns/submissions`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/submissions/post(submitPrompt)`.
    internal func submitPrompt(
        path: Operations.SubmitPrompt.Input.Path,
        headers: Operations.SubmitPrompt.Input.Headers,
        body: Operations.SubmitPrompt.Input.Body
    ) async throws -> Operations.SubmitPrompt.Output {
        try await submitPrompt(Operations.SubmitPrompt.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/turns/{turnID}`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/{turnID}/get(getTurn)`.
    internal func getTurn(
        path: Operations.GetTurn.Input.Path,
        headers: Operations.GetTurn.Input.Headers
    ) async throws -> Operations.GetTurn.Output {
        try await getTurn(Operations.GetTurn.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /v1/sessions/{sessionID}/turns/{turnID}/abort`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/turns/{turnID}/abort/post(abortTurn)`.
    internal func abortTurn(
        path: Operations.AbortTurn.Input.Path,
        headers: Operations.AbortTurn.Input.Headers
    ) async throws -> Operations.AbortTurn.Output {
        try await abortTurn(Operations.AbortTurn.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/vcs`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/vcs/get(getSessionVCS)`.
    internal func getSessionVCS(
        path: Operations.GetSessionVCS.Input.Path,
        headers: Operations.GetSessionVCS.Input.Headers
    ) async throws -> Operations.GetSessionVCS.Output {
        try await getSessionVCS(Operations.GetSessionVCS.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /v1/sessions/{sessionID}/vcs/events`.
    /// - Remark: Generated from `#/paths//v1/sessions/{sessionID}/vcs/events/get(streamSessionVCS)`.
    internal func streamSessionVCS(
        path: Operations.StreamSessionVCS.Input.Path,
        headers: Operations.StreamSessionVCS.Input.Headers
    ) async throws -> Operations.StreamSessionVCS.Output {
        try await streamSessionVCS(Operations.StreamSessionVCS.Input(
            path: path,
            headers: headers
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
internal enum Servers {}
