// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    internal enum Schemas {
        /// - Remark: Generated from `#/components/schemas/Scratchpad`.
        internal struct Scratchpad: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Scratchpad/content`.
            internal var content: Swift.String
            /// - Remark: Generated from `#/components/schemas/Scratchpad/ownerSessionId`.
            internal var ownerSessionId: Swift.String
            /// - Remark: Generated from `#/components/schemas/Scratchpad/revision`.
            internal var revision: Swift.String
            /// - Remark: Generated from `#/components/schemas/Scratchpad/updatedAt`.
            internal var updatedAt: Swift.String
            /// Creates a new `Scratchpad`.
            ///
            /// - Parameters:
            ///   - content:
            ///   - ownerSessionId:
            ///   - revision:
            ///   - updatedAt:
            internal init(
                content: Swift.String,
                ownerSessionId: Swift.String,
                revision: Swift.String,
                updatedAt: Swift.String
            ) {
                self.content = content
                self.ownerSessionId = ownerSessionId
                self.revision = revision
                self.updatedAt = updatedAt
            }
            internal enum CodingKeys: String, CodingKey {
                case content
                case ownerSessionId
                case revision
                case updatedAt
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.content = try container.decode(
                    Swift.String.self,
                    forKey: .content
                )
                self.ownerSessionId = try container.decode(
                    Swift.String.self,
                    forKey: .ownerSessionId
                )
                self.revision = try container.decode(
                    Swift.String.self,
                    forKey: .revision
                )
                self.updatedAt = try container.decode(
                    Swift.String.self,
                    forKey: .updatedAt
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "content",
                    "ownerSessionId",
                    "revision",
                    "updatedAt"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/StringErrorEnvelope`.
        internal struct StringErrorEnvelope: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/StringErrorEnvelope/error`.
            internal var error: Swift.String
            /// Creates a new `StringErrorEnvelope`.
            ///
            /// - Parameters:
            ///   - error:
            internal init(error: Swift.String) {
                self.error = error
            }
            internal enum CodingKeys: String, CodingKey {
                case error
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.error = try container.decode(
                    Swift.String.self,
                    forKey: .error
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "error"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/UpdateScratchpadInput`.
        internal struct UpdateScratchpadInput: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/UpdateScratchpadInput/content`.
            internal var content: Swift.String
            /// - Remark: Generated from `#/components/schemas/UpdateScratchpadInput/expectedRevision`.
            internal var expectedRevision: Swift.String
            /// Creates a new `UpdateScratchpadInput`.
            ///
            /// - Parameters:
            ///   - content:
            ///   - expectedRevision:
            internal init(
                content: Swift.String,
                expectedRevision: Swift.String
            ) {
                self.content = content
                self.expectedRevision = expectedRevision
            }
            internal enum CodingKeys: String, CodingKey {
                case content
                case expectedRevision
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.content = try container.decode(
                    Swift.String.self,
                    forKey: .content
                )
                self.expectedRevision = try container.decode(
                    Swift.String.self,
                    forKey: .expectedRevision
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "content",
                    "expectedRevision"
                ])
            }
        }
    }
}
