// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    internal enum Schemas {
        /// - Remark: Generated from `#/components/schemas/CapacityExceededError`.
        internal struct CapacityExceededError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/CapacityExceededError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case capacityExceeded = "capacity_exceeded"
            }
            /// - Remark: Generated from `#/components/schemas/CapacityExceededError/code`.
            internal var code: Components.Schemas.CapacityExceededError.CodePayload
            /// - Remark: Generated from `#/components/schemas/CapacityExceededError/message`.
            internal var message: Swift.String
            /// Creates a new `CapacityExceededError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.CapacityExceededError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.CapacityExceededError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/ConflictError`.
        internal struct ConflictError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ConflictError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case conflict = "conflict"
            }
            /// - Remark: Generated from `#/components/schemas/ConflictError/code`.
            internal var code: Components.Schemas.ConflictError.CodePayload
            /// - Remark: Generated from `#/components/schemas/ConflictError/message`.
            internal var message: Swift.String
            /// Creates a new `ConflictError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.ConflictError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.ConflictError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/ForbiddenError`.
        internal struct ForbiddenError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ForbiddenError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case forbidden = "forbidden"
            }
            /// - Remark: Generated from `#/components/schemas/ForbiddenError/code`.
            internal var code: Components.Schemas.ForbiddenError.CodePayload
            /// - Remark: Generated from `#/components/schemas/ForbiddenError/message`.
            internal var message: Swift.String
            /// Creates a new `ForbiddenError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.ForbiddenError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.ForbiddenError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/GitHubPullRequest`.
        internal struct GitHubPullRequest: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/GitHubPullRequest/number`.
            internal var number: Swift.Int
            /// - Remark: Generated from `#/components/schemas/GitHubPullRequest/url`.
            internal var url: Swift.String
            /// Creates a new `GitHubPullRequest`.
            ///
            /// - Parameters:
            ///   - number:
            ///   - url:
            internal init(
                number: Swift.Int,
                url: Swift.String
            ) {
                self.number = number
                self.url = url
            }
            internal enum CodingKeys: String, CodingKey {
                case number
                case url
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.number = try container.decode(
                    Swift.Int.self,
                    forKey: .number
                )
                self.url = try container.decode(
                    Swift.String.self,
                    forKey: .url
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "number",
                    "url"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/InstanceMismatchError`.
        internal struct InstanceMismatchError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/InstanceMismatchError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case instanceMismatch = "instance_mismatch"
            }
            /// - Remark: Generated from `#/components/schemas/InstanceMismatchError/code`.
            internal var code: Components.Schemas.InstanceMismatchError.CodePayload
            /// - Remark: Generated from `#/components/schemas/InstanceMismatchError/message`.
            internal var message: Swift.String
            /// Creates a new `InstanceMismatchError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.InstanceMismatchError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.InstanceMismatchError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/InternalError`.
        internal struct InternalError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/InternalError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case _internal = "internal"
            }
            /// - Remark: Generated from `#/components/schemas/InternalError/code`.
            internal var code: Components.Schemas.InternalError.CodePayload
            /// - Remark: Generated from `#/components/schemas/InternalError/message`.
            internal var message: Swift.String
            /// Creates a new `InternalError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.InternalError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.InternalError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/InvalidHostError`.
        internal struct InvalidHostError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/InvalidHostError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case invalidHost = "invalid_host"
            }
            /// - Remark: Generated from `#/components/schemas/InvalidHostError/code`.
            internal var code: Components.Schemas.InvalidHostError.CodePayload
            /// - Remark: Generated from `#/components/schemas/InvalidHostError/message`.
            internal var message: Swift.String
            /// Creates a new `InvalidHostError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.InvalidHostError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.InvalidHostError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/InvalidRequestError`.
        internal struct InvalidRequestError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/InvalidRequestError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case invalidRequest = "invalid_request"
            }
            /// - Remark: Generated from `#/components/schemas/InvalidRequestError/code`.
            internal var code: Components.Schemas.InvalidRequestError.CodePayload
            /// - Remark: Generated from `#/components/schemas/InvalidRequestError/message`.
            internal var message: Swift.String
            /// Creates a new `InvalidRequestError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.InvalidRequestError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.InvalidRequestError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/LimitExceededError`.
        internal struct LimitExceededError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/LimitExceededError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case limitExceeded = "limit_exceeded"
            }
            /// - Remark: Generated from `#/components/schemas/LimitExceededError/code`.
            internal var code: Components.Schemas.LimitExceededError.CodePayload
            /// - Remark: Generated from `#/components/schemas/LimitExceededError/message`.
            internal var message: Swift.String
            /// Creates a new `LimitExceededError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.LimitExceededError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.LimitExceededError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/NotFoundError`.
        internal struct NotFoundError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NotFoundError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case notFound = "not_found"
            }
            /// - Remark: Generated from `#/components/schemas/NotFoundError/code`.
            internal var code: Components.Schemas.NotFoundError.CodePayload
            /// - Remark: Generated from `#/components/schemas/NotFoundError/message`.
            internal var message: Swift.String
            /// Creates a new `NotFoundError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.NotFoundError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.NotFoundError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/ProtocolMismatchError`.
        internal struct ProtocolMismatchError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ProtocolMismatchError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case protocolMismatch = "protocol_mismatch"
            }
            /// - Remark: Generated from `#/components/schemas/ProtocolMismatchError/code`.
            internal var code: Components.Schemas.ProtocolMismatchError.CodePayload
            /// - Remark: Generated from `#/components/schemas/ProtocolMismatchError/message`.
            internal var message: Swift.String
            /// Creates a new `ProtocolMismatchError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.ProtocolMismatchError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.ProtocolMismatchError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/Scratchpad`.
        internal struct Scratchpad: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Scratchpad/content`.
            internal var content: Swift.String
            /// - Remark: Generated from `#/components/schemas/Scratchpad/ownerSessionId`.
            internal var ownerSessionId: Swift.String
            /// - Remark: Generated from `#/components/schemas/Scratchpad/revision`.
            internal var revision: Swift.String
            /// - Remark: Generated from `#/components/schemas/Scratchpad/updatedAt`.
            internal var updatedAt: Swift.String
            /// Creates a new `Scratchpad`.
            ///
            /// - Parameters:
            ///   - content:
            ///   - ownerSessionId:
            ///   - revision:
            ///   - updatedAt:
            internal init(
                content: Swift.String,
                ownerSessionId: Swift.String,
                revision: Swift.String,
                updatedAt: Swift.String
            ) {
                self.content = content
                self.ownerSessionId = ownerSessionId
                self.revision = revision
                self.updatedAt = updatedAt
            }
            internal enum CodingKeys: String, CodingKey {
                case content
                case ownerSessionId
                case revision
                case updatedAt
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.content = try container.decode(
                    Swift.String.self,
                    forKey: .content
                )
                self.ownerSessionId = try container.decode(
                    Swift.String.self,
                    forKey: .ownerSessionId
                )
                self.revision = try container.decode(
                    Swift.String.self,
                    forKey: .revision
                )
                self.updatedAt = try container.decode(
                    Swift.String.self,
                    forKey: .updatedAt
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "content",
                    "ownerSessionId",
                    "revision",
                    "updatedAt"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/ScratchpadErrorDetails`.
        internal struct ScratchpadErrorDetails: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ScratchpadErrorDetails/scratchpad`.
            internal var scratchpad: Components.Schemas.Scratchpad
            /// Creates a new `ScratchpadErrorDetails`.
            ///
            /// - Parameters:
            ///   - scratchpad:
            internal init(scratchpad: Components.Schemas.Scratchpad) {
                self.scratchpad = scratchpad
            }
            internal enum CodingKeys: String, CodingKey {
                case scratchpad
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.scratchpad = try container.decode(
                    Components.Schemas.Scratchpad.self,
                    forKey: .scratchpad
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "scratchpad"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/ScratchpadInvalidContentError`.
        internal struct ScratchpadInvalidContentError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ScratchpadInvalidContentError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case scratchpadInvalidContent = "scratchpad_invalid_content"
            }
            /// - Remark: Generated from `#/components/schemas/ScratchpadInvalidContentError/code`.
            internal var code: Components.Schemas.ScratchpadInvalidContentError.CodePayload
            /// - Remark: Generated from `#/components/schemas/ScratchpadInvalidContentError/message`.
            internal var message: Swift.String
            /// Creates a new `ScratchpadInvalidContentError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.ScratchpadInvalidContentError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.ScratchpadInvalidContentError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/ScratchpadMigrationRequiredError`.
        internal struct ScratchpadMigrationRequiredError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ScratchpadMigrationRequiredError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case scratchpadMigrationRequired = "scratchpad_migration_required"
            }
            /// - Remark: Generated from `#/components/schemas/ScratchpadMigrationRequiredError/code`.
            internal var code: Components.Schemas.ScratchpadMigrationRequiredError.CodePayload
            /// - Remark: Generated from `#/components/schemas/ScratchpadMigrationRequiredError/message`.
            internal var message: Swift.String
            /// Creates a new `ScratchpadMigrationRequiredError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.ScratchpadMigrationRequiredError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.ScratchpadMigrationRequiredError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/ScratchpadRevisionConflictError`.
        internal struct ScratchpadRevisionConflictError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ScratchpadRevisionConflictError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case scratchpadRevisionConflict = "scratchpad_revision_conflict"
            }
            /// - Remark: Generated from `#/components/schemas/ScratchpadRevisionConflictError/code`.
            internal var code: Components.Schemas.ScratchpadRevisionConflictError.CodePayload
            /// - Remark: Generated from `#/components/schemas/ScratchpadRevisionConflictError/details`.
            internal var details: Components.Schemas.ScratchpadErrorDetails
            /// - Remark: Generated from `#/components/schemas/ScratchpadRevisionConflictError/message`.
            internal var message: Swift.String
            /// Creates a new `ScratchpadRevisionConflictError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - details:
            ///   - message:
            internal init(
                code: Components.Schemas.ScratchpadRevisionConflictError.CodePayload,
                details: Components.Schemas.ScratchpadErrorDetails,
                message: Swift.String
            ) {
                self.code = code
                self.details = details
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case details
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.ScratchpadRevisionConflictError.CodePayload.self,
                    forKey: .code
                )
                self.details = try container.decode(
                    Components.Schemas.ScratchpadErrorDetails.self,
                    forKey: .details
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "details",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/ScratchpadRevisionExhaustedError`.
        internal struct ScratchpadRevisionExhaustedError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ScratchpadRevisionExhaustedError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case scratchpadRevisionExhausted = "scratchpad_revision_exhausted"
            }
            /// - Remark: Generated from `#/components/schemas/ScratchpadRevisionExhaustedError/code`.
            internal var code: Components.Schemas.ScratchpadRevisionExhaustedError.CodePayload
            /// - Remark: Generated from `#/components/schemas/ScratchpadRevisionExhaustedError/message`.
            internal var message: Swift.String
            /// Creates a new `ScratchpadRevisionExhaustedError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.ScratchpadRevisionExhaustedError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.ScratchpadRevisionExhaustedError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/ScratchpadTooLargeError`.
        internal struct ScratchpadTooLargeError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ScratchpadTooLargeError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case scratchpadTooLarge = "scratchpad_too_large"
            }
            /// - Remark: Generated from `#/components/schemas/ScratchpadTooLargeError/code`.
            internal var code: Components.Schemas.ScratchpadTooLargeError.CodePayload
            /// - Remark: Generated from `#/components/schemas/ScratchpadTooLargeError/message`.
            internal var message: Swift.String
            /// Creates a new `ScratchpadTooLargeError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.ScratchpadTooLargeError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.ScratchpadTooLargeError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/ScratchpadUnavailableError`.
        internal struct ScratchpadUnavailableError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ScratchpadUnavailableError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case scratchpadUnavailable = "scratchpad_unavailable"
            }
            /// - Remark: Generated from `#/components/schemas/ScratchpadUnavailableError/code`.
            internal var code: Components.Schemas.ScratchpadUnavailableError.CodePayload
            /// - Remark: Generated from `#/components/schemas/ScratchpadUnavailableError/message`.
            internal var message: Swift.String
            /// Creates a new `ScratchpadUnavailableError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.ScratchpadUnavailableError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.ScratchpadUnavailableError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/ScratchpadUnsupportedError`.
        internal struct ScratchpadUnsupportedError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ScratchpadUnsupportedError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case scratchpadUnsupported = "scratchpad_unsupported"
            }
            /// - Remark: Generated from `#/components/schemas/ScratchpadUnsupportedError/code`.
            internal var code: Components.Schemas.ScratchpadUnsupportedError.CodePayload
            /// - Remark: Generated from `#/components/schemas/ScratchpadUnsupportedError/message`.
            internal var message: Swift.String
            /// Creates a new `ScratchpadUnsupportedError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.ScratchpadUnsupportedError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.ScratchpadUnsupportedError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/SessionVCSStatus`.
        internal struct SessionVCSStatus: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/SessionVCSStatus/cwd`.
            internal var cwd: Swift.String
            /// - Remark: Generated from `#/components/schemas/SessionVCSStatus/sessionId`.
            internal var sessionId: Swift.String
            /// - Remark: Generated from `#/components/schemas/SessionVCSStatus/status`.
            internal var status: Components.Schemas.VCSStatus?
            /// Creates a new `SessionVCSStatus`.
            ///
            /// - Parameters:
            ///   - cwd:
            ///   - sessionId:
            ///   - status:
            internal init(
                cwd: Swift.String,
                sessionId: Swift.String,
                status: Components.Schemas.VCSStatus? = nil
            ) {
                self.cwd = cwd
                self.sessionId = sessionId
                self.status = status
            }
            internal enum CodingKeys: String, CodingKey {
                case cwd
                case sessionId
                case status
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.cwd = try container.decode(
                    Swift.String.self,
                    forKey: .cwd
                )
                self.sessionId = try container.decode(
                    Swift.String.self,
                    forKey: .sessionId
                )
                self.status = try container.decodeIfPresent(
                    Components.Schemas.VCSStatus.self,
                    forKey: .status
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "cwd",
                    "sessionId",
                    "status"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/UnauthorizedError`.
        internal struct UnauthorizedError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/UnauthorizedError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case unauthorized = "unauthorized"
            }
            /// - Remark: Generated from `#/components/schemas/UnauthorizedError/code`.
            internal var code: Components.Schemas.UnauthorizedError.CodePayload
            /// - Remark: Generated from `#/components/schemas/UnauthorizedError/message`.
            internal var message: Swift.String
            /// Creates a new `UnauthorizedError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.UnauthorizedError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.UnauthorizedError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/UnavailableError`.
        internal struct UnavailableError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/UnavailableError/code`.
            internal enum CodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case unavailable = "unavailable"
            }
            /// - Remark: Generated from `#/components/schemas/UnavailableError/code`.
            internal var code: Components.Schemas.UnavailableError.CodePayload
            /// - Remark: Generated from `#/components/schemas/UnavailableError/message`.
            internal var message: Swift.String
            /// Creates a new `UnavailableError`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - message:
            internal init(
                code: Components.Schemas.UnavailableError.CodePayload,
                message: Swift.String
            ) {
                self.code = code
                self.message = message
            }
            internal enum CodingKeys: String, CodingKey {
                case code
                case message
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.code = try container.decode(
                    Components.Schemas.UnavailableError.CodePayload.self,
                    forKey: .code
                )
                self.message = try container.decode(
                    Swift.String.self,
                    forKey: .message
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "code",
                    "message"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/UpdateScratchpadInput`.
        internal struct UpdateScratchpadInput: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/UpdateScratchpadInput/content`.
            internal var content: Swift.String
            /// - Remark: Generated from `#/components/schemas/UpdateScratchpadInput/expectedRevision`.
            internal var expectedRevision: Swift.String
            /// Creates a new `UpdateScratchpadInput`.
            ///
            /// - Parameters:
            ///   - content:
            ///   - expectedRevision:
            internal init(
                content: Swift.String,
                expectedRevision: Swift.String
            ) {
                self.content = content
                self.expectedRevision = expectedRevision
            }
            internal enum CodingKeys: String, CodingKey {
                case content
                case expectedRevision
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.content = try container.decode(
                    Swift.String.self,
                    forKey: .content
                )
                self.expectedRevision = try container.decode(
                    Swift.String.self,
                    forKey: .expectedRevision
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "content",
                    "expectedRevision"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/VCSHead`.
        internal struct VCSHead: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/VCSHead/kind`.
            internal enum KindPayload: String, Codable, Hashable, Sendable, CaseIterable {
                case branch = "branch"
                case detached = "detached"
                case unborn = "unborn"
            }
            /// - Remark: Generated from `#/components/schemas/VCSHead/kind`.
            internal var kind: Components.Schemas.VCSHead.KindPayload
            /// - Remark: Generated from `#/components/schemas/VCSHead/name`.
            internal var name: Swift.String?
            /// - Remark: Generated from `#/components/schemas/VCSHead/oid`.
            internal var oid: Swift.String?
            /// Creates a new `VCSHead`.
            ///
            /// - Parameters:
            ///   - kind:
            ///   - name:
            ///   - oid:
            internal init(
                kind: Components.Schemas.VCSHead.KindPayload,
                name: Swift.String? = nil,
                oid: Swift.String? = nil
            ) {
                self.kind = kind
                self.name = name
                self.oid = oid
            }
            internal enum CodingKeys: String, CodingKey {
                case kind
                case name
                case oid
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.kind = try container.decode(
                    Components.Schemas.VCSHead.KindPayload.self,
                    forKey: .kind
                )
                self.name = try container.decodeIfPresent(
                    Swift.String.self,
                    forKey: .name
                )
                self.oid = try container.decodeIfPresent(
                    Swift.String.self,
                    forKey: .oid
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "kind",
                    "name",
                    "oid"
                ])
            }
        }
        /// - Remark: Generated from `#/components/schemas/VCSStatus`.
        internal struct VCSStatus: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/VCSStatus/dirty`.
            internal var dirty: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/VCSStatus/head`.
            internal var head: Components.Schemas.VCSHead
            /// - Remark: Generated from `#/components/schemas/VCSStatus/pullRequest`.
            internal var pullRequest: Components.Schemas.GitHubPullRequest?
            /// - Remark: Generated from `#/components/schemas/VCSStatus/root`.
            internal var root: Swift.String
            /// Creates a new `VCSStatus`.
            ///
            /// - Parameters:
            ///   - dirty:
            ///   - head:
            ///   - pullRequest:
            ///   - root:
            internal init(
                dirty: Swift.Bool,
                head: Components.Schemas.VCSHead,
                pullRequest: Components.Schemas.GitHubPullRequest? = nil,
                root: Swift.String
            ) {
                self.dirty = dirty
                self.head = head
                self.pullRequest = pullRequest
                self.root = root
            }
            internal enum CodingKeys: String, CodingKey {
                case dirty
                case head
                case pullRequest
                case root
            }
            internal init(from decoder: any Swift.Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)
                self.dirty = try container.decode(
                    Swift.Bool.self,
                    forKey: .dirty
                )
                self.head = try container.decode(
                    Components.Schemas.VCSHead.self,
                    forKey: .head
                )
                self.pullRequest = try container.decodeIfPresent(
                    Components.Schemas.GitHubPullRequest.self,
                    forKey: .pullRequest
                )
                self.root = try container.decode(
                    Swift.String.self,
                    forKey: .root
                )
                try decoder.ensureNoAdditionalProperties(knownKeys: [
                    "dirty",
                    "head",
                    "pullRequest",
                    "root"
                ])
            }
        }
    }
}
