name = "kit"
ard = ">= 0.43.0"
target = "go"

[build.values]
version = { type = "Str", default = "dev", release = true }
commit = { type = "Str", default = "unknown", release = true }

[dependencies]
cooper = { path = "../../../cooper" }
