name = "kit"
ard = ">= 0.42.0"
target = "go"

[build.values]
version = { type = "Str", default = "dev", release = true }
commit = { type = "Str", default = "unknown", release = true }

[dependencies]
cooper = { git = "https://github.com/akonwi/cooper.git", commit = "ecaf8d48b589dab2e7970052542a4ebed0c140d4" }
